name: inter_libras
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  auto_size_text: ^2.1.0
  avatar_glow: ^2.0.1
  dio: ^4.0.0
  flag: ^3.2.2
  flutter:
    sdk: flutter
  flutter_mobx: ^1.1.0+2
  flutter_modular: ^2.0.1
  flutter_svg: ^0.19.2+1
  google_fonts: ^2.0.0
  mobx: ^1.2.1+4
  model_viewer: ^0.8.1
  speech_to_text: ^3.2.0

dev_dependencies:
  mockito: ^4.1.3
  modular_codegen: 
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    #  - assets/model_3d
    - assets/icons/
